# General
title: Your awesome title
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur, dolores aliquam doloribus expedita error quod eos, inventore autem est ducimus numquam quisquam, deserunt saepe in quasi excepturi accusamus quas optio.
baseurl: '/example-1' # the subpath of your site
url: 'https://your-landing.github.io' # the base hostname & protocol for your site


# Header
author: Juan King

favicon:
  url: 'favicon.ico'
  type: 'image/x-icon' # .ico - image/x-icon, .png - image/png, .gif - image/gif

social:
  image: 'assets/placeholder.png'
  type: 'image/png' # .png - image/png, .jpg/.jpeg - image/jpeg, .svg - image/svg+xml, .webp - image/webp, .gif - image/gif
  width: 1200
  height: 630

analytics: false


# Navbar
brand:
  type: title # title, image, text
  image: 'assets/placeholder-brand.jpg' # 4:1, e.g. 120x30px
  text: Example Title
navbar:
  - name: Home
    url: '#'
  - name: About
    url: '#about'
  - name: Services
    dropdown:
      - name: Title One
      - name: Contacts
        url: '#contacts'
        active: true
      - name: Portfolio
        url: '#portfolio'
        active: false
        divider: true
      - name: Title Two
      - name: Translate
        url: '#translate'
  - name: Description
    description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, temporibus.
  - name: Pricing
    url: '#pricing'
  - name: <i class="fas fa-shopping-cart"></i> # shop
    url: '#shop'
navbar_color: dark # light, dark


# Blog
blog_button: Read more


# Projects
projects_button: All


# Footer
copyright: '2010'
footer:
  - name: Features
    links:
      - name: Cool stuff
        url: '#'
      - name: Random feature
        url: '#'
      - name: Team feature
        url: '#'
      - name: Stuff for developers
        url: '#'
      - name: Another one
        url: '#'
      - name: Last time
        url: '#'
  - name: Resources
    links:
      - name: Business
        url: '#'
      - name: Education
        url: '#'
      - name: Government
        url: '#'
      - name: Gaming
        url: '#'
      - name: Resource
        url: '#'
      - name: Another resource
        url: '#'
      - name: Final resource
        url: '#'
  - name: About
    links:
      - name: Team
        url: '#'
      - name: Locations
        url: '#'
      - name: Privacy
        url: '#'
      - name: Terms
        url: '#'


# Core (don't change it if you don't know how to use it)
collections:
  blocks:
    output: true
  projects:
    output: true
permalink: /blog/:title/
# exclude: ['test']
